import colorama
from colorama import Fore,Style,Back
import time
time.sleep(2)
V='''
███████╗██████╗░
██╔════╝██╔══██╗
█████╗░░██████╦╝
██╔══╝░░██╔══██╗
██║░░░░░██████╦╝
╚═╝░░░░░╚═════╝░
    CODED BY SHAIK AFRID'''   
print(Fore.YELLOW+Style.BRIGHT+V)
print(Fore.RED+Style.BRIGHT+"A=LOGIN")
print(Fore.GREEN+Style.BRIGHT+                       
print(Fore.RED+Style.BRIGHT+"B=FAKE LOGIN")
X=input(Fore.GREEN+Style.BRIGHT+"ENTER UR OPTION:-")
if X==A:
        U="afrid"
        p="17030143"
        s="LOGIN"
        
        
        
        
        print(Fore.YELLOW+Style.BRIGHT+"SELECTED LOGIN :)")
        A=input(Fore.GREEN+Style.BRIGHT+"ENTER USERNAME :-")
        if A==u:
                print("sucess")
                
        else:
                print("wrong username")
        
        
        
        
        
        
        B=input(Fore.GREEN+Style.BRIGHT+"ENTER PASSWORD :-")
        if B==p:
                print("sucess")
        else :
                
                print("wrong password")
        S=input(Fore.YELLOW+Style.BRIGHT+"ENTER HIGH SECURITY KEY:-")
        if S==s:
                print("sucess")
        else :
                print("wrong")
        
        
        
        
                
                
        
        
        
        

      













































