import colorama
from colorama import Fore,Back,Style
import time
logo='''
███████╗██████╗░
██╔════╝██╔══██╗
█████╗░░██████╦╝
██╔══╝░░██╔══██╗
██║░░░░░██████╦╝
╚═╝░░░░░╚═════╝░
        CODED BY SHAIK AFRID:)'''
time.sleep(3)
print(Fore.RED+Style.BRIGHT+logo)
time.sleep(3)
a="LOGIN"
b="FAKE LOGIN"
A=input(Fore.YELLOW+Style.BRIGHT+"ENTER UR NAME:-")
print(Fore.ORANGE+Style.BRIGHT+"HELLO"+A)
print(Fore.YELLOW+Style.BRIGHT+"a="+a)
print(Fore.YELLOW+Style.BRIGHT+"b="+b)
time.sleep(5)
x=input(Fore.YELLOW+Style.BRIGHT+"SELECT UR OPTION:-")
if x==a:
  Z="password"
  time.sleep(4)
  print(Fore.YELLOW+Style.BRIGHT+"LOADING...../////")
  print (Fore.RED+Stle.BRIGHT+"SELECTED LOGIN:)")
  username=input(Fore.RED+Style.BRIGHT+"ENTER UR USERNAME :-")
  password==input(Fore.RED+Style.BRIGHT+"ENTER UR PASSWORD:-")
  if password!=Z:
    print("SORRY PASSWORD WRONG")
    time.sleep(3)
    print(Fore.YELLOE+Style.BRIGHT+"CONACT ADMIN FOR PASSWORD")
  





  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
